/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import org.junit.Test;

public class MainTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
