/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// https://github.com/fathzer/javaluator?tab=readme-ov-file
import com.fathzer.soft.javaluator.DoubleEvaluator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
