/*
 * This source file was generated by the Gradle 'init' task
 */
package org.operations;

import static org.junit.Assert.assertEquals;
import org.junit.Test;

public class OperationsTest {
    @Test 
    public void appHasAGreeting() {
        Operations classUnderTest = new Operations("10");
        classUnderTest.log("2");
        String output = classUnderTest.evaluate();

        assertEquals("3.3219280948873626", output);
    }
}
